[package]
name = "buffex"
version = "0.0.2"
edition = "2021"

authors = ["lino <lino_snsalias@outlook.com>"]
description = "BUFFer EXtensions: ring buffer and buffer chaining."
repository = "https://github.com/ljsnogard/buffex"
keywords = ["buffer", "io"]
categories = ["algorithms", "no-std"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
abs_buff = { git = "https://github.com/ljsnogard/abs_buff.git", branch = "dev-0.2.0" }
atomex = { git = "https://github.com/ljsnogard/atomex-rs.git", branch = "dev/0.1.1" }
recl-slices = { git = "https://github.com/ljsnogard/recl-slices.git", commit = "1c886c69341fe82d1768eb8b93bcc0cc63b57264" }

pin-project = { version = "1.1.*" }
smallvec = { version = "1.13", features = [] }

[dev-dependencies]
mm_ptr = { git = "https://github.com/ljsnogard/mm_ptr.git", branch = "dev/0.1.2" }
core_malloc = { git = "https://github.com/ljsnogard/core_malloc.git", branch = "dev/0.1.2" }
spmv-oneshot = { git = "https://github.com/ljsnogard/spmv-oneshot.git", branch = "dev/0.1.2" }

env_logger = { version = "0.11.*" }
log = { version = "0.4.*" }

chrono = { version = "0.4.*" }
rand = { version = "0.8.*" }
tokio = { version = "1", features = ["full"] }
